name: Deploy Preview

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  deploy:
    uses: ./.github/workflows/deployment.yaml
    needs: [tests]
    secrets: inherit
    with:
      environment: develop

